### ISSUE TITLE
Error When Trying to Open World Maps

### ISSUE THREAD

**Issue by hrace009** [halysondev/npcgeneditor#1]
Hello, I got error when trying to open the World Map.
Error Details:
```
An unexpected error occurred: Unable to load DLL 'DevIL.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Time: 28/09/2024 07:39:18 
System.DllNotFoundException: Unable to load DLL 'DevIL.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DevIL.Unmanaged.IL.ilInit()
   at DevIL.Unmanaged.IL.Initialize() in E:\backup150124\Documents\npcgen1\DevILNET\DevIL.Unmanaged\IL.cs:line 399
   at LBLIBRARY.PWHelper.LoadDDSImage(Byte[] ByteArray) in E:\backup150124\Documents\npcgen1\LBLIBRARY\LBLIBRARY\PWHelper.cs:line 116
   at NpcGenDataEditor.Form1.LinkMaps(List`1 l, String MapName) in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor\Form1.cs:line 1275
   at NpcGenDataEditor.Form1.<>c__DisplayClass498_0.<ShowOnMapsButton_Click>b__0() in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor\Form1.cs:line 1810
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
InnerException: 
 
InnerException StackTrace: 
  
```

Thanks

**Comment by hrace009** [comment]
Okay, problem solve using this  [https://openil.sourceforge.net/download.php](https://openil.sourceforge.net/download.php)
