### ISSUE TITLE
Error when open map and selecting item from list

### ISSUE THREAD

**Issue by hrace009** [halysondev/npcgeneditor#2]
Hello,

I manage to open the map, but it error when trying to select NPC from list. Error detail:
```
An unexpected error occurred: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "NpcGenDataEditor.Properties.Resources.resources" was correctly embedded or linked into assembly "Npcgen Editor By Luka and Updated by Haly" at compile time, or that all the satellite assemblies required are loadable and fully signed.
Time: 28/09/2024 07:49:16 
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "NpcGenDataEditor.Properties.Resources.resources" was correctly embedded or linked into assembly "Npcgen Editor By Luka and Updated by Haly" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
   at NpcGenDataEditor.Properties.Resources.get_arrow() in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor.Properties\Resources.cs:line 69
   at NpcGenDataEditor.ShowLocationWindow.GetCoordinates(List`1 ls) in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor\ShowLocationWindow.cs:line 46
   at NpcGenDataEditor.Form1.ExistenceGrid_CellChanged(Object sender, EventArgs e) in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor\Form1.cs:line 3131
   at System.Windows.Forms.DataGridView.OnCurrentCellChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
InnerException: 
 
InnerException StackTrace: 
  
```

![image](https://github.com/user-attachments/assets/7bf866b7-0838-4a0b-b11f-cc943276c8ff)

Thanks

**Comment by hrace009** [comment]
> Hello,
> 
> I manage to open the map, but it error when trying to select NPC from list. Error detail:
> 
> ```
> An unexpected error occurred: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "NpcGenDataEditor.Properties.Resources.resources" was correctly embedded or linked into assembly "Npcgen Editor By Luka and Updated by Haly" at compile time, or that all the satellite assemblies required are loadable and fully signed.
> Time: 28/09/2024 07:49:16 
> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "NpcGenDataEditor.Properties.Resources.resources" was correctly embedded or linked into assembly "Npcgen Editor By Luka and Updated by Haly" at compile time, or that all the satellite assemblies required are loadable and fully signed.
>    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
>    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>    at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
>    at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
>    at NpcGenDataEditor.Properties.Resources.get_arrow() in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor.Properties\Resources.cs:line 69
>    at NpcGenDataEditor.ShowLocationWindow.GetCoordinates(List`1 ls) in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor\ShowLocationWindow.cs:line 46
>    at NpcGenDataEditor.Form1.ExistenceGrid_CellChanged(Object sender, EventArgs e) in E:\backup150124\Documents\npcgen1\npcgen\NpcGenDataEditor\Form1.cs:line 3131
>    at System.Windows.Forms.DataGridView.OnCurrentCellChanged(EventArgs e)
>    at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
>    at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
>    at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
>    at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
>    at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.DataGridView.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> InnerException: 
>  
> InnerException StackTrace: 
>   
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7691118/371714983-7bf866b7-0838-4a0b-b11f-cc943276c8ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0ODUwMjMsIm5iZiI6MTcyNzQ4NDcyMywicGF0aCI6Ii83NjkxMTE4LzM3MTcxNDk4My03YmY4NjZiNy0wODM4LTRhMGItYjExZi1jYzk0MzI3NmM4ZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDA1MjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGEzOGJjNDUwYWEwYjRhMDVhYWUzNmQxYTkxNDA3YmFjNTVkZjY5ZWVjYTU0YmMxYjE1ZjlhYWE5MWJjNThmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gu7TZmv5bu0Tla8J0YKmVMFwoUul5cAJ1SeYV_NEocc)
> 
> Thanks

i have try using the old surface 1.4.5 version, still got this error

**Comment by hrace009** [comment]
i have try using old surfaces.pck from old files 1.4.5, still got this error

**Comment by hrace009** [comment]
Done, fixed
